### ISSUE TITLE
Support logging for to papertrail

### ISSUE THREAD

**Issue by tobiasmcnulty** [caktus/ansible-role-k8s-web-cluster#2]
https://help.papertrailapp.com/kb/configuration/configuring-centralized-logging-from-kubernetes/#log-from-the-standard-docker-streams (or `fluentd`)

**Comment by dpoirier** [comment]
Maybe we could support a few logging mechanisms in the role? Papertrail and Cloudwatch (via fluentd) seem like two good candidates to start with.

**Comment by vkurup** [comment]
Papertrail is now well supported (using logspout), thanks to #6. Not sure if we want to close this, or create a new issue for fluentd/cloudwatch?

**Comment by copelco** [comment]
Agreed about #6 and we can create a new issue for future functionality
